Create match
UdL-EPS-SoftArch/mypadel-api pull request #39
Opened 2017-10-12 11:49 UTC by mrg20

Now a match has a match creator.

2017-10-12 22:27 UTC, bergacat1 requested changes
In the tests, the Match must be created through the API, not directly through the repository. Moreover, you have to test that the creator of the match is correctly stored doing another GET to "http://localhost/publicMatches/1/matchCreator". The current test is not even testing that the match has a creator since the link would be present even if there were not a creator.

2017-10-12 22:31 UTC, mrg20 commented
Understood the part of testing the match creator

2017-10-13 09:04 UTC, mrg20 commented
Changes done, now testing the match creator. No changes on match creation since is created in a post request (like all the other object creations).

2017-10-16 12:02 UTC, bergacat1 approved these changes

2017-10-16 12:02 UTC, merged