Confirm match result
UdL-EPS-SoftArch/mypadel-api pull request #69
Opened 2017-10-31 22:54 UTC by deinok

Closes #6

2017-11-02 11:50 UTC, bergacat1 requested changes
First of all, in the scenarios of "MatchResultVerification" you say you are going to test as Player and as Admin but you login as Admin in all cases.

Secondly, you should test that the MatchResultVerification has been correctly linked with MatchResult and the Player. You should also do that for the tests of MatchResult, checking that the MatchResult is linked with the Players and Match.

Finally, you should check that a Player can only verify results of his matches.

2017-11-27 16:46 UTC, deinok commented
@bergacat1 So how can we link a matchResult to a match, and all this things in gherkins?
Its okey as a toy tool but we waste more time testing that the frameworks we use are working as expected than implementing real features.

Should we implement a dictionary<string,object> that saves the results of one gherkins sentence to be able to get it in the next sentence?

2017-11-28 09:14 UTC, bergacat1 commented
The correct way would be to identify the match you want to verify by its characteristics (specially the date) so that the sentence would be reusable from anywhere. In your case, an example would be:
  ```
Scenario: A player creates a new MatchResultVerification
	Given I login as "testplayer@mypadel.cat" with password "password"
	And The player with email "testplayer@mypadel.cat" played a public match on "date"
	And There is a MatchResult for the public match player on "date" 
	When I agree through a MatchResultVerification with the MatchResult of the match played on "date"
	Then The response code is 201
	And A new MatchResultVerification is added for the MatchResult of the match played on "date"
```
By this way, you could also test that only players who played a certain match can submit or verify its result.

2017-12-04 15:40 UTC, deinok commented
@bergacat1 Creiem que ja esta

2017-12-04 16:13 UTC, bergacat1 requested changes
En l'últim 'step', us falta comprovar que el MatchResultVerification queda correctament relacionat amb el MatchResult i el Player.

2017-12-04 16:13 UTC, bergacat1 commented on src/test/java/cat/udl/eps/softarch/mypadel/steps/MatchResultVerificationCreateSteps.java
> +	}
Aquí haurieu de comprovar que la MatchResultVerification ha quedat correctament relacionada amb el MatchResult i el Player.

2017-12-04 16:44 UTC, deinok commented
@bergacat1 fet

2017-12-04 18:52 UTC, bergacat1 requested changes
El link estaria present encara que no hi hagués cap element associat. Heu de fer un GET a les URIs de les relacions i comprovar que retorna un 200. Si fossin null, retornaria 404.

2017-12-05 22:05 UTC, deinok commented
@bergacat1 Fet.

PD: Si per cada propietat de navegacio ens hem de complicar tant, potse val la pena que implementem el protocol GraphQL http://graphql.org/

Al treball hem conseguit fer-ho amb navegacio infinita i cargan les entitats amb de forma "explicita" (sense el famos problema dels ORMs de "SELECT N+1").
Tambe ens simplificarie el treball al Frontend

2017-12-05 22:15 UTC, bergacat1 approved these changes
Ara perfecte. Molt interessant el GraphQL, però per aquest projecte millor no complicar-nos a aquestes altures...

2017-12-05 22:16 UTC, merged